### ISSUE TITLE
ArcGIS online issue with mbtiles layers

### ISSUE THREAD

**Issue by kurt-hectic** [klokantech/tileserver-php#10]
Hello,

I have noticed that ArcGIS online has a problem selecting the right layer when multiple mbtiles layers are made available by tileserver-php.

The map editor in ArcGIS allows to add an OGC WMTS layer. After inputting the URL to a WMTS service, it issues a getCapabilities an lets the user select from all available layers.
The issue is that ArcGIS seems to always load the first layer, no matter which one was actually selected. This is if I have "1-map, 2-map, 3-map" tile layers available, what is shown in the ArcGIS map is always "1-map", even though I selected 2-map or 3-map.

I have verified that what is requested by ArcGIS is actually the first layer, thus excluding that the mapserver somehow delivers the wrong content. (by checking webserver logs)
I have also verified that ArgGIS can in general correctly handle selecting one of multiple available layers (by pointing it to v2.suite.opengeo.org/geoserver/gwc/service/wmts/, where the selected layer is shown, no matter which one was selected).

I thus believe that ArcGIS somehow incorrectly parses the getCapabilities request of tileserver-php, or that some element ArgGIS requires is missing in the request.
Comparing a working and a non-working example of getCapabilities requests, I noticed differences in the "TileMatrixSetLimits" elements. 

I do not know enough about the WMTS getCapabilities spec to tell what could trigger this behaviour.

Any clues why ArcGIS always requests the first layer from a tileserver-php server?

thanks a lot
kurt

**Comment by NitinIIRS** [comment]
Hi there,

I am adding the published map to Arcmap as WMTS service. It was added on Arc catalog without any error but it is not dispalyed on Viewer though can be seen on TOC. Please help!!
