### ISSUE TITLE
klokantech Geolocation Control not working

### ISSUE THREAD

**Issue by zulkifil** [klokantech/tileserver-php#105]
tileserver php not show klokantech Geolocation Control on maps.

**Comment by pathmapper** [comment]
Some browsers need SSL encryption (https) for this function, maybe this causes the issue.

**Comment by zulkifil** [comment]
@pathmapper you are right ... it display and work with SSL only. Is it possible make it work with both SSL and non SSL or any other work around?

**Comment by daliborjanak** [comment]
Yes, this was the point why we remove it by default. People write us that it doesn't work. But the problem is with https...
