### ISSUE TITLE
[Question] How to display street names when hosting everything locally?

### ISSUE THREAD

**Issue by unzan** [klokantech/tileserver-php#107]
I've followed the instructions on https://openmaptiles.org/docs/host/tileserver-php/ and host everything locally but [the map doesn't show street names][1]. If I open the mbtiles using tileserver.php's viewer,  [the street name is visible on hover][2] ("Jalan Tol Padalarang"). How do I put this on the map?

[1]: https://i.imgur.com/CzdHDxp.png
[2]: https://i.imgur.com/mM8hYyj.png

**Comment by daliborjanak** [comment]
This could be a problem with fonts? (cors?)Labels are defined in style of a map

**Comment by unzan** [comment]
Turns out it's `name:latin` that is the problem. I'm using the mbtiles for country Indonesia and `name:latin` doesn't show anything. Replacing that with just `name` fixed it. Anyway, thank you.
