### ISSUE TITLE
Serving Vector Tiles that have been extracted from mbtiles file

### ISSUE THREAD

**Issue by dylanparry** [klokantech/tileserver-php#110]
Hi,

I'm having problem serving PBF files that have been extracted from an mbtiles file. I have placed them in a directory within `/var/www` on my Docker container, and the files themselves are being served but aren't usable due to some missing headers.

![image](https://user-images.githubusercontent.com/3692873/28669883-1256f9a0-72ce-11e7-8956-c71ed4da9ddc.png)

There are several headers missing from these requests. Firstly, the CORS header isn't present so OpenLayers can't use the returned files if they're on a different host. This isn't the case when using the mbtiles format.

Also missing are the mime type for PBF files, so the returned files have no file type associated with them and are interpreted as plain text.

Finally, the default PBF files exported by Tippecanoe and extracted via MBUtils are gzipped. There is no header to tell the browser that the files have been gzipped, so it's unable to read them once they've been downloaded.

For comparison, when accessing the tiles via the mbtiles format, I get the following headers:

![image](https://user-images.githubusercontent.com/3692873/28670547-26023818-72d1-11e7-9915-fc87af41ebe7.png)

As such, although suggesting to export the files to make performance better, it currently doesn't appear to be able to serve the files at all so I have to resort to leaving them inside the mbtiles file. Is there something I am doing wrong when it comes to setting things up to serve the extracted files?

Any help would be greatly appreciated!

Thanks,

Dylan

**Comment by sheub** [comment]
Same problem here with the gzip compression: I have downloaded an mbtile map from openmaptiles, extracted it to xyz directory to increase performance, but I can display the maps only on Firefox... on Chrome and IE it does appear. Please help, I am stock...
Thanks,

Sébastien

**Comment by daliborjanak** [comment]
CORS problem: Tileserver-php returns cross-origin *  if PHP returns tiles if you have to serve directly via apache you need to uncomment following lines in htaccess or set it in apache:
https://github.com/klokantech/tileserver-php/blob/master/.htaccess#L18

Extracted tiles: TIleserver-php is not tested with extracted pbf from mbtiles. We can test and add this functionality in future or you can pay support hours to add it. It's an opensource, you can createč the půlull request with fix :-) You can run it easily with mbtiles without unpacking...

**Comment by daliborjanak** [comment]
Yes, this is confusing as I see. To clear this: TileServer-php was first time designed to raster support from folder and mbtiles produced by MapTiler www.maptiler.com. Later we add support for vector tiles from mbtiles downloadable from openmaptiles.org. This part survived from raster implementation. I will clear this in code later, we don't have time for opensource development right now

**Comment by daliborjanak** [comment]
So I test it and it works, There are the commands which are working. To unpack the tiles I have used mb-util and than unpack:
```
./mb-util --image_format=pbf countries.mbtiles countries
gzip -d -r -S .pbf *
find . -type f -exec mv '{}' '{}'.pbf \;
```

TIleserver will serve this tiles correctly but there might be some problem with the centring of a map.

**Comment by StephenAtty** [comment]
Dylan - what else did you have to do to get this to work? When I try to use the extracted files it crashes out with an error in evented.js

**Comment by dylanparry** [comment]
@StephenAtty if I'm honest, I don't remember as it was so long ago. It was over a year ago, so it's likely that there have been changes to this project since then too, so anything I did might not be relevant now anyway. Sorry I can't be of any help.
