### ISSUE TITLE
Running with IIS 8

### ISSUE THREAD

**Issue by nadnerb33** [klokantech/tileserver-php#113]
I'm trying to get the tileserver-php up and running with IIS8/Win Server 2012 because unfortunately that's what I have to use for this project.

PHP is installed, configured and working with other projects, but I'm getting an error when I load /tileserver-php/tileserver.php
Alert:

    JSON metadata file is not valid. Please check configuration of your server.

Chrome Console:

    /tileserver-php/tileserver.php?/index.json Failed to load resource: net::ERR_CONNECTION_REFUSED

I have managed to convert some of the htaccess to web.config

    <rewrite>
            <rules>
                <rule name="Rule 1" stopProcessing="true">
                    <match url="^(.+).jpeg$" ignoreCase="false" />
                    <action type="Rewrite" url="{R:1}.jpg" />
                </rule>
                <rule name="Rule 2" stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{R:1}" pattern="^(tileserver\.php)" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="tileserver.php?/{R:1}" appendQueryString="true" />
                </rule>
               
                <rule name="Rule 3" stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{R:1}" pattern="^(tileserver\.php)" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="tileserver.php?/{R:1}" appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>

but there are some which I can't figure out:

    # Not modified HTTP 302
    RewriteRule .* - [E=HTTP_IF_MODIFIED_SINCE:%{HTTP:If-Modified-Since}]
    RewriteRule .* - [E=HTTP_IF_NONE_MATCH:%{HTTP:If-None-Match}]

I know in readme.md it mentions to install IIRF, but it won't install on Win2012/IIS8 - doesn't seem to have been updated for years and others report it doesn't install on 7.5.

Has anyone successfully got this running with IIS or have any pointers?

Cheers

**Comment by Levente0xFFFF** [comment]
Hi,

It is funny because I had the same issue in less an hour you have posted this.
I could fix this with a workaround:
Open tileserver.php and modify line #1237 by changing

`$config['protocol'] = ((isset($_SERVER['HTTPS']) or $_SERVER['SERVER_PORT'] == '443') or $xForwarded) ? 'https' : 'http';`
to
`$config['protocol'] = ((isset($_SERVER['HTTPS']) or $_SERVER['SERVER_PORT'] == '443') or $xForwarded) ? 'http' : 'http';`

BTW I'm using IIS 7.5 on Win7 and I converted the mod_rewrite rules into the IIS built-in URL Rewrite rules by importing the content of .htaccess.
It could not convert these two rules but they are not seem to be so important:
`RewriteRule .* - [E=HTTP_IF_MODIFIED_SINCE:%{HTTP:If-Modified-Since}]`
`RewriteRule .* - [E=HTTP_IF_NONE_MATCH:%{HTTP:If-None-Match}]`

**Comment by nadnerb33** [comment]
Awesome, such a simple fix and it is now working! Thanks for replying.
Out of interest, how did you figure out that was the problem?

**Comment by Levente0xFFFF** [comment]
Well, there is a very similar issue already opened:
[https://github.com/klokantech/tileserver-php/issues/96](url)
Also, I had a more meaningful error message in Google Chrome console:
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR                             /TileServer/index.json
