### ISSUE TITLE
tileserver API Source Code

### ISSUE THREAD

**Issue by zulkifil** [klokantech/tileserver-php#114]
Is it is possible that one can add or remove api functionalities of online mapping libraries in tileserver so tileserver show that function by default with existing source code of the online mapping libraries? I want to add some api functions to default source code of online mapping libraries and turn on some functions so i can get all complete source code. 

For example i want to turn on  streetViewControl by defualt and add fullscreeenControl etc.

**Comment by daliborjanak** [comment]
Js client is closed-source. It is just "starter" or "helper" for a quick start. If you need to use different viewer just copy the code from templates. And use JSONs from tileserver-php. If you need to change it  use a custom template, implemented in:
https://github.com/klokantech/tileserver-php/issues/31
