### ISSUE TITLE
JSON metadata file is not valid. Please check configuration of your server

### ISSUE THREAD

**Issue by toton6868** [klokantech/tileserver-php#116]
I am trying to use this tileserver php with and mbtiles generated from Tilemill. Its returning "JSON metadata file is not valid. Please check configuration of your server" from server. What I am missing?

**Comment by daliborjanak** [comment]
I couldn't test it with tilemill tiles but it is standard mbtiles so it might work. Can you provide a broken tileset?

**Comment by toton6868** [comment]
[sample.zip](https://github.com/klokantech/tileserver-php/files/1445677/sample.zip)
Here is a sample mbtiles file which I have exported from Tilemill project. Its showing nothing

**Comment by daliborjanak** [comment]
In my latest installation is OK. See:
![image](https://user-images.githubusercontent.com/1891090/32435853-80e5edd6-c2e2-11e7-8622-32fa3f62091d.png)

There might be something wrong with a configuration of your server. Rewrites etc. I couldn't fix it without seeing it. Sorry. So this is not a bug with our software or reading of a data

**Comment by toton6868** [comment]
I am using wamp Version 3.1.0. I just copied the zip archive and put it in my wamp directory. then put the mbtile file. do I need to configure anything? The vector.mbtiles is loading but raster.mbtiles is not loading. Beside did you saw the bdmaps url? What is the problem with that?

**Comment by daliborjanak** [comment]
My mistake sorry, I didn't see URL. Problem is here: http://www.bdmaps.net/tileserver/index.json - this JSON is not valid.
You have there a "template" for grit which is wrongly passed to JSON. Are you planning to use utfgrids?
My tileserver returns this json from your sample:
``` javascript
{
bounds: [
90.3689,
23.7299,
90.3901,
23.7468
],
minzoom: 15,
maxzoom: 16,
name: "Distribution_Only",
description: "",
attribution: "",
legend: "",
template: "",
version: "1.0.0",
format: "png",
basename: "sample",
profile: "mercator",
scale: 1,
tiles: [
"http://localhost/tech/tileserver-php/sample/{z}/{x}/{y}.png"
],
tilejson: "2.0.0",
scheme: "xyz",
grids: [
"http://localhost/tech/tileserver-php/sample/{z}/{x}/{y}.grid.json"
]
}
```

**Comment by toton6868** [comment]
I am getting the same json for the sample file.

**Comment by daliborjanak** [comment]
So if you don't want to use grid layers open mbtiles as sqlite3 database (it is so used e.g. SQLite browser http://sqlitebrowser.org/) and delete or modify columns in table metadata. There are fields which are wrongly encoded into tilejson. I don't have time to patch and debug tileserver now (and I need data which breaks it). This might solve your issue

**Comment by toton6868** [comment]
Sample file contains the right format Metadata but Still there is no luck.

**Comment by daliborjanak** [comment]
There is another file on your server which brakes it. TileServer brows all datasets in the folder and uses it. You have OpenMapTiles mbtiles here which brakes it.

**Comment by toton6868** [comment]
Here is my json and out put
```

[  
   {  
      "bounds":[  
         90.2726,
         23.6577,
         90.5177,
         23.914
      ],
      "center":"90.39,23.758,15",
      "format":"png",
      "minzoom":10,
      "maxzoom":18,
      "scale":"1",
      "id":"osmbd",
      "attribution":"",
      "description":"",
      "name":"OSMBD",
      "legend":"",
      "tilejson":"2.0.0",
      "template":"",
      "version":"1.0.0",
      "basename":"dhk_main",
      "profile":"mercator",
      "tiles":[  
         "http://localhost/klokantech/dhk_main/{z}/{x}/{y}.png"
      ],
      "scheme":"xyz",
      "grids":[  
         "http://localhost/klokantech/dhk_main/{z}/{x}/{y}.grid.json"
      ]
   },
   {  
      "bounds":[  
         90.3689,
         23.7299,
         90.3901,
         23.7468
      ],
      "minzoom":15,
      "maxzoom":16,
      "name":"Distribution_Only",
      "description":"",
      "attribution":"",
      "legend":"",
      "template":"",
      "version":"1.0.0",
      "format":"png",
      "basename":"sample",
      "profile":"mercator",
      "scale":1,
      "tiles":[  
         "http://localhost/klokantech/sample/{z}/{x}/{y}.png"
      ],
      "tilejson":"2.0.0",
      "scheme":"xyz",
      "grids":[  
         "http://localhost/klokantech/sample/{z}/{x}/{y}.grid.json"
      ]
   }
]
```

![p1](https://user-images.githubusercontent.com/1884539/32439606-ad336eea-c319-11e7-8656-712e65605402.png)
![p2](https://user-images.githubusercontent.com/1884539/32439607-ad83ce8a-c319-11e7-947f-7e0c070f28cb.png)

**Comment by pathmapper** [comment]
> You have OpenMapTiles mbtiles here which brakes it.

Maybe related to https://github.com/openmaptiles/openmaptiles/issues/379 ?

**Comment by daliborjanak** [comment]
Maybe, this examples are now deleted :-( @pathmapper your issue will be solved in omt 3.8. We will let you know in your ticket.

This error "JSON metadata file is not valid. Please check the configuration of your server" generally says that index.json is broken so please go to [tileserver-home]/index.json and look what is wrong there. This was an issue with broken "JSON" filed in TileJSON

**Comment by dingfengboo** [comment]
I have the same problem when I use mbtiles generated by myself (use openmaptiles).
But it is ok for the data download from https://openmaptiles.com/downloads/planet/.

**Comment by daliborjanak** [comment]
This is known bug: https://github.com/openmaptiles/openmaptiles/issues/379 I will fix it soon

**Comment by animaux** [comment]
This error is turning up again just now. Could it be because of changes in https://cdn.klokantech.com/tileviewer/v1/index.js ?

**Comment by marcosci** [comment]
Is there any chance to get an older version of the index.js, that was still functioning?

I am facing the same error, just starting a vanilla tileserver-php within my XAMPP docker.

**Comment by Kobrairaq** [comment]
Same problem here is there a solution?

**Comment by dieterdreist** [comment]
maybe I am wrong, but from comparing the metadata within the mbtiles (with sqlite3) and the output I get in the browser, it seems tileserver.php is escaping apostrophes in the json. Apostrophes are not escaped in json. It seems it is done in `addslashes` in line 193
