### ISSUE TITLE
Link to certain coordinates

### ISSUE THREAD

**Issue by Malauch** [klokantech/tileserver-php#117]
Hi,
I have hosted some map via tileserver and it works great. I would like to link to certain location on that map. Is it possible? The best option would be with some marker.

I have in mind something like this: https://www.openstreetmap.org/?mlat=50.9113&mlon=15.3148#map=14/50.9113/15.3148 but to my map hosted using tileserver.

**Comment by daliborjanak** [comment]
You mean to add coordinates to a hash. This is not possible now. TileViewer's is routing is based on hashes. Just copy code example and start building your own map app
