### ISSUE TITLE
Doc disambiguation : Tile size 256x256 limitation

### ISSUE THREAD

**Issue by Fractaliste** [klokantech/tileserver-php#129]
Hi,

I'm using your server to perform POCs comparison between Openlayer and Mapbox.

I see [in the documentation](https://github.com/klokantech/tileserver-php#limits-of-actual-implementation) that one of your tool limitation is:

> All tiles must be 256x256 pixels.

Do you mean that tiles put in the data directory should be 256x256 pixel or do you mean that vector tiles outputed by the server can only be 256x256 pixel?

I ask it because as far as I understand last Mapbox's documentation, it needs 512 pixel size whereas Openlayer use more common 256px and at the moment I failed to make it working with Mapbox : the tilesever returns 204 status code so I suspect that the server does not understand 512px's x,y bounds into the url...

**Comment by daliborjanak** [comment]
Hi, 512px tiles are implemented. This is wrongly written in the readme. Thank you for a report. This was implemented in 18 see https://github.com/klokantech/tileserver-php/issues/18 
I will fix readme

**Comment by Fractaliste** [comment]
Ok so I should be able to request vector tiles with last Mapbox-gl-js version (0.45 whereas the tile server preview run on 0.12).

With Openlayer traditionnal requests work well:
> http://localhost:1724/tileserver-php-master/tileserver.php/2017-07-03_france_paris/13/4149/2817.pbf

But with Mapbox-gl-js I got 204 HTTP status: 
 > http://localhost:1724/tileserver-php-master/tileserver.php/2017-07-03_france_paris/14/8295/10746@2x.pbf

I try the following URL I found on the page you link:
```
wget -qO - http://localhost:80/tileserver-php-master/tileserver.php/2017-07-03_france_paris/@2x.json --no-proxy 
TileServer: unknown map @2x
```

Should I understand that my .mbtile are not Hight-DPI compliant? I got them from https://openmaptiles.com/downloads/planet/ I thought they were Mappbox complient?
