### ISSUE TITLE
Max zoom level only 14

### ISSUE THREAD

**Issue by onny** [klokantech/tileserver-php#138]
Hey,
I'm using tileserver-php with vector tiles I purchased on openmaptiles.org. Everything works fine with Mapbox GL JS until I reach zoom level 14. After zooming in further, the whole map disappears.
According to openmaptiles it's possible to "overzoom" to much higher levels.
I guess the restriction is hardcoded into the mbtiles file, where sqlite3 tells me:
```
sqlite3 osm-2018-10-15-v3-8-germany_karlsruhe.mbtiles         
sqlite> select * from metadata;
[...]
maxzoom|14
[...]
```
How could I force higher zoom levels in tilesevrer-php?

Best regards,
Jonas

**Comment by daliborjanak** [comment]
Data from OMT are rendered to zoom 14. So the tileserver servers only to 14. You have to over zoom it in JavaScript client.

**Comment by onny** [comment]
Thank you @daliborjanak this was a good hint. It was not easy to figure out how Mapbox GL JS handles this. I referenced my custom style json file when initializing Mapbox:
```
<script>

var map = new mapboxgl.Map({
  container: 'map',
  style: 'json/style.json',
});

</script>
```
The crucial part was to specify maxzoom in the sources part:
```
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "tiles": ["http://localhost/tileserver/tileserver.php?/index.json?/osm-2018-10-15-v3-8-germany_karlsruhe/{z}/{x}/{y}.pbf"],
      "minzoom": 0,
      "maxzoom": 14
    }
  },
```
This means, that my tileset only supports zoom level 14. With this information Mapbox GL JS is able to overzoom to higher zoom levels ...
This was a bit confusing ^^

Best regards,
Jonas

**Comment by nmosinski** [comment]
> Thank you @daliborjanak this was a good hint. It was not easy to figure out how Mapbox GL JS handles this. I referenced my custom style json file when initializing Mapbox:
> 
> ```
> <script>
> 
> var map = new mapboxgl.Map({
>   container: 'map',
>   style: 'json/style.json',
> });
> 
> </script>
> ```
> 
> The crucial part was to specify maxzoom in the sources part:
> 
> ```
>   "sources": {
>     "openmaptiles": {
>       "type": "vector",
>       "tiles": ["http://localhost/tileserver/tileserver.php?/index.json?/osm-2018-10-15-v3-8-germany_karlsruhe/{z}/{x}/{y}.pbf"],
>       "minzoom": 0,
>       "maxzoom": 14
>     }
>   },
> ```
> 
> This means, that my tileset only supports zoom level 14. With this information Mapbox GL JS is able to overzoom to higher zoom levels ...
> This was a bit confusing ^^
> 
> Best regards,
> Jonas

That's indeed super confusing, I would never have guessed it. Thanks!
