### ISSUE TITLE
mbtiles from QGIS?

### ISSUE THREAD

**Issue by Skipper-is** [klokantech/tileserver-php#145]
I've tried to export some mbtiles from QGIS, to open in Tileserver.
The maps are present on the list:
![image](https://user-images.githubusercontent.com/28678069/62007172-454ad200-b142-11e9-9ff5-f266a6e89514.png)
But when I open them, there is no data:
![image](https://user-images.githubusercontent.com/28678069/62007183-64496400-b142-11e9-89da-42e76d4c1c00.png)
The tileserver.json also returns:
`TileServer: unknown map tileserver`
Don't know whether there are any dependencies I'm missing. I think I've got Sqlite3 (and the php mod as well), anything else (and any way of testing)?

If I reimport the tiles into QGIS, they work fine in QGIS

**Comment by daliborjanak** [comment]
Can you send us the link to the server and better to upload non-working data?

**Comment by Skipper-is** [comment]
The server is at [this link](https://home.skipper-iwb.co.uk/tileserver/)
And I have also uploaded the data to: [This address](http://home.skipper-iwb.co.uk/CollegeDSM.mbtiles)
The process I have been through to get the data is:
In QGIS - Reprojected some data (geoTIFF) from EPSG27700 to EPSG:3857 (gdalwarp)
Then exported it to a .mbtile using `gdal_translate -of MBTiles`

**Comment by daliborjanak** [comment]
You have wrongly configured appache or path in htacces. It works that you are running the script directly:
https://home.skipper-iwb.co.uk/tileserver/tileserver.php?/CollegeDSM/#CollegeDSM/ol3

So there is no issue with displaying QGIS tiles in tileserver-php

**Comment by Skipper-is** [comment]
Ok, how are they supposed to be configured? I just used the default .htaccess file that came with

**Comment by daliborjanak** [comment]
Configure path manually https://github.com/klokantech/tileserver-php/blob/master/tileserver.php#L15 or use RewriteBase https://github.com/klokantech/tileserver-php/blob/master/.htaccess#L9
