### ISSUE TITLE
GeoJSON editor integration

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-php#43]
It would be great to integrate a functionality for:
- [x] create and edit basic vector data on top of a tileset (add and edit markers, geonames for place search, transcriptions, or basic vectorization - markers, polygon, lines + attributes). Something like an integrated http://geojson.io/ or it's rewrite in OL3)
- [x] allow import of vector data (drag & drop of GeoJSON/SHP/KML ...) a la geojson.io
- [x] allow export / download (client side generators) a la geojson.io
- [x] link existing online vector data (url to a geojson) to a tileset. Multiple vector data may be linked.

It seems to me the best storage for small vector data like these is a GeoJSON format saved on GIST or a GitHub repo. Alternative would be a local storage in PHP, but it has disadvantages in interoperability and advantages in independence.

**Comment by mapnewbie** [comment]
Just wanted to know if this issue is being worked upon.
Thanks

**Comment by klokan** [comment]
All of this has been done.

It is now integrated with TileServer PHP - in the sidebar chose "Edit" tab.

For details see: http://www.maptiler.com/geoeditor/
