### ISSUE TITLE
PNG image from mbtiles file sometimes loads, sometimes not

### ISSUE THREAD

**Issue by arjendk** [klokantech/tileserver-php#44]
I'm having trouble showing a tiled map from an mbtiles-file. Some images, especially at higher zoomlevels, don't get displayed sometimes. The behaviour seems random; the same image sometimes is displayed, and sometimes not.

If you reload an image several times, you will see that it sometimes shows up correctly, but sometimes nothing is shown.

http://myserver.com/tiles/tileserver.php?/pc4_multi/17/67546/43194.png

(I've removed the real url to the server; please contact me if you'd like to test.)

A little debugging shows that when it isn't displayed, no data is returned from the query on the mbtiles database: $data == FALSE in line 311.

Any idea what causes this problem or how to diagnose it further?

**Comment by arjendk** [comment]
Addition: the same goes for UTFGrid!
http://dev.meseda.nl/tiles/tileserver.php?/pc4_multi/17/67546/43194.grid.json
(I added some code to return an empty grid when $data == false, this is not in the original tileserver.php.)

**Comment by arjendk** [comment]
Update: it does work correctly on my local Apache installation. Could this be a timing issue, or something to do with library versions (like SQLite)? Any suggestions how to find out more very welcome!

**Comment by klokan** [comment]
Thanks for the reports. We will try to reproduce this on our side - this sort of error is hard to fix.

What if you try to catch the exception and read the tile again?

**Comment by daliborjanak** [comment]
Hmm strange. Have you got error logs or something more?
Try to set base url manualy. Edit line 12 in tileserver.php: 
``` php
$config['baseUrls'] = array('myserver.com/tiles');
```
or add to path and /tileserver.php
``` php
$config['baseUrls'] = array('myserver.com/tiles/tileserver.php');
```

**Comment by arjendk** [comment]
No error occured so no error was logged nor could an exception be caught. The SQLite query just didn't return anything sometimes.

We were able to solve this problem by setting the connection persistance of the database, PDO::ATTR_PERSISTENT to false (line 254). It doesn't seem to affect performance very much, as far as we can tell. Hope this helps!

**Comment by klokan** [comment]
No action on our side here. Closing.
