### ISSUE TITLE
Installation Trouble

### ISSUE THREAD

**Issue by funkytupperware** [klokantech/tileserver-php#45]
I copied my .mbtiles file to the tileserver directory.  When I go to view them, I can only see the base map, not the map I created in Tile Mill.

```
#0 /var/www/XXX.com/maps/tileserver.php(254): PDO->__construct('sqlite:geograph...', '', '', Array)
#1 /var/www/XXX.com/maps/tileserver.php(165): Server->DBconnect('geography-class...')
#2 /var/www/XXX.com/maps/tileserver.php(81): Server->metadataFromMbtiles('geography-class...')
#3 /var/www/XXX.com/maps/tileserver.php(457): Server->setDatasets()
#4 [internal function]: Server->getHtml()
#5 /var/www/XXX.com/maps/tileserver.php(1452): call_user_func(Array)
#6 /var/www/XXX.com/maps/tileserver.php(29): Router::serve(Array)
#7 {main}
```
Does anyone know what I'm doing wrong? Thanks.

**Comment by klokan** [comment]
It very probably means your PHP hosting does not support SQLite.

**Comment by funkytupperware** [comment]
Sorry, I thought I deleted the error message from my previous questions.  I'm running a VPS and after I installed SQLite, the above errors went away.  However, when I go to the tileserver-php directory, it lists the available maps, but does not render them: http://s4.postimg.org/g8inxt2q5/tileserver.jpg
Also, when I click on the available maps, I dont see the map I rendered, only the various base maps.
Aside from SQLlite and mod_rewrites, are there any other dependencies that need to be installed? 

Thanks

**Comment by klokan** [comment]
No there is no other dependency.
Everything required for installation is described in the README.md.

Your bug report does not give any clue - and is not reproducible on our side.

Provide url to your server and more information about your system (operating system, webserver, link to phpinfo, etc) or any sort of error message you get - otherwise there is no way how to help you.

**Comment by funkytupperware** [comment]
It looks like there was an issue with the installation of sqlite.  I re-installed it on a new server and now everything works fine.  Thanks you.
