### ISSUE TITLE
Error in coloring

### ISSUE THREAD

**Issue by LionelR** [klokantech/tileserver-php#55]
The mbtiles are generated with TileMill from shapefiles, on the same region, with some predefined colors. Each time the online interface is refreshed, the maps are rendered in differents colors, like you can see on the two first screenshots. 
With leaflet (or OL, ...), some tiles are rendered in a color and all with another, depending on the zoom factor (last screenshot).
This problem doesn't seem to happen with the tileserver.php from infostreams.

I use the last tileserver.php from github, with Nginx on Ubuntu 14.04.

![screenshot_003](https://cloud.githubusercontent.com/assets/490118/10280997/bbdead08-6b71-11e5-95d1-f60cf5bafd72.jpg)
![screenshot_002](https://cloud.githubusercontent.com/assets/490118/10280998/bbe76290-6b71-11e5-9b91-8afbfba43fe2.jpg)
![screenshot_004](https://cloud.githubusercontent.com/assets/490118/10281000/c1be04a8-6b71-11e5-9234-1bb0593d2c89.jpg)

**Comment by LionelR** [comment]
The same problem happens with a unique mbtile file in the folder.

**Comment by klokan** [comment]
Could you please provide us with a link to such tileserver instance?
How can we reproduce the problem on our side?

There is nothing like this happening on other servers - so what do you special?

What you describe may sound like a cache problem in your web browser, in case you have uploaded different files under the same name.

To identify a different problem we must see and reproduce the problem on our side. Please provide more information.

**Comment by LionelR** [comment]
After searching it seems to be effectively a web browser's cache problem like you said. So it's not a tileserver issue.
