### ISSUE TITLE
Hybrid tile format support

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-php#59]
MapTiler 0.6.3 supports rendering of hybrid tiles without extension and with new metadata.

TileServer-PHP project should to support this format now.

There is also a pending Pull Request #58 on ArcGIS implementation of Hybrid - to be cleaned and merged.

**Comment by daliborjanak** [comment]
I fixed bug related with changes in this issue and utf grid. 28aba6f9e20188c0e79a6ca3639adc3397cc6d79

This looks stable now.

**Comment by klokan** [comment]
Thanks! TODO: Update of the WMTS Proxy: https://github.com/klokan/wmts.maptiler.com/issues/3
