### ISSUE TITLE
tileserver not rendering properly - dependency issue?

### ISSUE THREAD

**Issue by heaversm** [klokantech/tileserver-php#61]
Hi - I was able to successfully install tileserver php on my local server, but when installing on a remote digital ocean server, the tileserver URL comes up, but when I copy the same .mbtiles file into the tileserver folder, the tileserver app doesn't work (see image). I can see no visible errors.

The dependencies are listed as PHP and mod_rewrite / htaccess. I noticed it sets up a sqqllite db - is that  some sort of dependency I need to check in to? Can you think of anything else that might be keeping it from functioning properly?

**Comment by heaversm** [comment]
<img width="1752" alt="screen shot 2015-12-15 at 3 28 07 pm" src="https://cloud.githubusercontent.com/assets/520541/11823154/7a8cef3e-a340-11e5-82e3-6ae03efd19de.png">

**Comment by heaversm** [comment]
Hi - I figured this out, sort of - the server needed php5-sqlite (which should probably be listed as a dependency in readme).

```
sudo apt-get install php5-sqlite
```

 But now I have a new issue, which is that the tileserver attempts to load tiles from this address:

```
http://107.170.120.88/tileserver/extra5/11/329/792.png
```

but the address my server needs is

```
http://107.170.120.88/tileserver/tileserver.php/extra5/11/329/792.png
```

Do you know how best to modify the script so that the `tileserver.php` gets inserted into all json and tile URLs?

**Comment by klokan** [comment]
Dependencies README.md updated.

Are you sure you have the .htaccess next to tileserver.php?

URL should look like: http://107.170.120.88/tileserver/extra5/11/329/792.png

**Comment by heaversm** [comment]
Thanks for the quick response. I do, but for some reason that URL doesn't work - it only works if I insert tileserver.php after tileserver directory, like:

```http://107.170.120.88/tileserver/tileserver.php/extra5/11/329/792.png```

so far I haven't found an htaccess rule that will work to insert this though.

**Comment by heaversm** [comment]
Is there some easy way I can just manually insert tileserver.php into the script?

**Comment by klokan** [comment]
.htaccess is in this repository. Prepared. You should unpack it to your server.

This ticket is about dependency issue (php5-sqlite) missing in documentation. It has been fixed.

Open a different ticket if there is another issue, please.

Maybe you can try the checker php - which tells you issues on your server - see #48
