### ISSUE TITLE
syntax error on PHP 5.2.17,

### ISSUE THREAD

**Issue by stephankn** [klokantech/tileserver-php#63]
tileserver.php is not working and ends with a syntax error.

Parse error: syntax error, unexpected '[' in /home/webuser/domains/example.com/public_html/map/tileserver/tileserver.php on line 344

Webhosting uses PHP 5.2.17
I believe the used syntax is only valid from 5.4+ and should be replaced by the array() function.

not working on 5.2:

          //detect image type from file
          $mimetypes = ['gif', 'jpeg', 'png'];

changed to:

          //detect image type from file
          $mimetypes = array('gif', 'jpeg', 'png');

makes is work.

**Comment by daliborjanak** [comment]
I thing we will not support PHP 5.2. Officially is not supported also with 5.3 and 5.4. See: http://php.net/supported-versions.php

You can use release of old version 1.0 here: https://github.com/klokantech/tileserver-php/releases
It has support for 5.2

**Comment by klokan** [comment]
@daliborjanak is the array() vs [] the only line with problem for compatibility with PHP 5.2+?
We could use the travis to check the syntax of PHP in future - but is it the only problem?

**Comment by daliborjanak** [comment]
I thing yes but hybrid tile support will also not work. We couldn't test it easily. Better to leave old versions of PHP and link to 1.0 in my opinion. This bracket declaration is supported only in PHP >= 5.4 so 5.3 is also out.

**Comment by klokan** [comment]
OK. I Agree. We may push this to the checker #48.

Ideally - the tileserver.php itself should report what is the problem - if there is one - but only on request for HTML front page and only if it does not significantly slow down the response on default HTML page...

**Comment by stephankn** [comment]
If you plan on changing the requirements to require something newer than PHP5.2, please change the requirements you documented for it. The webspace I had access to unfortunately was stuck with the quite old 5.2

Currently it reads: **"PHP 5.2+ with SQLite module (php5-sqlite)"**
https://github.com/klokantech/tileserver-php/blame/master/README.md#L41

**Comment by klokan** [comment]
@daliborjanak I am afraid the old PHP happens to be on a many of web hostings for quite some time...

Travis seems to support 5.2 as the oldest PHP version. I would be keen to test syntax against HHVM as well. See: https://github.com/travis-ci-examples/php/blob/master/.travis.yml and https://github.com/klokantech/tileserver-php/tree/travis

**Comment by klokan** [comment]
Another person with the same problem:
https://groups.google.com/d/msg/maptiler/wJL09ntucEw/roqnfx2VEAAJ

**Comment by klokan** [comment]
Bug introduced here https://github.com/klokantech/tileserver-php/blame/master/tileserver.php#L344

To be fixed @daliborjanak
