### ISSUE TITLE
Correct detection of format

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/tileserver-php#66]
TileJSON doesn't specyfy format. If it's not set then we are sending PNG. We need to parse format from "tiles" parameter. Chenge will be on this line:
https://github.com/klokantech/tileserver-php/blob/master/tileserver.php#L241

    function parseFormat($url){
      $pos = strrpos($url, '.');
      $mime = trim(substr($url, $pos + 1));
      return $mime;
    }
    if (!array_key_exists('format', $layerMetadata)) {
      if (in_array(parseFormat($requestUrl), $this->availableFormats)) {
        $layerMetadata['format'] = parseFormat($requestUrl);
      }elseif(in_array(parseFormat($layerMetadata['tiles'][0]), $this->availableFormats)){
        $layerMetadata['format'] = parseFormat($layerMetadata['tiles'][0]);
      } else {
        $layerMetadata['format'] = 'png';
      }
    }

**Comment by klokan** [comment]
Duplicate to #67. Closing
