### ISSUE TITLE
WMTS topLeftCorner axis orientation

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/tileserver-php#70]
TopLeftCorner in tileMatrixSet defines two coordinates (x, y). In some coordinate systems like 4326 which has different axe orientation are the coordinates switched (y, x).
See:
http://gis.stackexchange.com/questions/120325/what-is-proper-succession-of-coordinates-while-specifying-topleftcorner-in-tilem

OL3 implementation:
https://github.com/openlayers/ol3/blob/master/src/ol/tilegrid/wmtstilegrid.js#L101

Proj4 4.8+ implementation:
https://trac.osgeo.org/proj/wiki/GenParms#Axisorientation

**Comment by klokan** [comment]
Results of research:
- EPSG:4326 is special and always have switched axis in WMTS.
- all systems (geodetic or projected) which in WKT definition has first AXIS set to EAST value, should be switched. Examples:
  - EPSG:3857: AXIS["X",EAST],AXIS["Y",NORTH]
  - EPSG:32633: AXIS["Easting",EAST],AXIS["Northing",NORTH]

**Comment by daliborjanak** [comment]
Finally we are removed axies parameter. The order of coords is based on type of system (geographic or projected). Tileserver is parsing it now from proj4 string if is provided. Implemented. Tested
