### ISSUE TITLE
Question: I need to let the Tileserver to point to tiles in a directory NOT in the Webserver Root directory

### ISSUE THREAD

**Issue by Ahmedgis** [klokantech/tileserver-php#75]
I need to let the **Tileserver** to **point to** tiles in a directory **NOT** in the **Webserver Root directory**.

i.e:

**My Apache root**: C:/wamp/www
**The TileServer** : C:/wamp/www/tileserver
**My Tiles in**        : C:/Tiles/Satellite

Thanks

**Comment by klokan** [comment]
Copy tiles and the tileserver.php and .htaccess to your  C:/wamp/www/tileserver.

This is not a place to discuss support. Free community support is provided to users of MapTIler (http://www.maptiler.com/) in the online forum. Commercial support is available as well.
See: http://www.maptiler.com/support/
