### ISSUE TITLE
WMTS does not serve deep zoom levels

### ISSUE THREAD

**Issue by chriswalker88** [klokantech/tileserver-php#76]
It seems that MBTiles created in MapTiler with zoomlevels above 18 start to pixelate when you zoom in while accessing via WMTS on desktop platforms. 

The tiles look fine in the web interface.

**Comment by klokan** [comment]
Can you provide any technical data - links to example, screenshot proving this problem.

How to reproduce the problem?

**Comment by klokan** [comment]
Sample data provided now. It is installation of latest TileServerPHP on local server.
The issue seems to be in maxzoom limit to 18 in WMTS Capabilities.

Have to verify and fix - possibly also in wmts.maptiler.com.

**Comment by daliborjanak** [comment]
This could be because we are generating default googlemapstilematrix set only to 18. Flowing line:
https://github.com/klokantech/tileserver-php/blob/master/tileserver.php#L840
It is possible to render deepest with custom profile.

@klokan What will be the new limit? 22 OSM.org brakes on 19. Sometimes you need larger for aerial photos.
@chriswalker88 Which zoomlevels are you uses?

**Comment by daliborjanak** [comment]
NOTE: Before we created dynamic generation of tilmatrixset, old tilematrix set has also 18 zooms.
Google maps has limit 21 for basemap. For areal it from 20 goes to oblique images

**Comment by klokan** [comment]
Default googlemapstilematrix set should run with `max(18,layer.maxzoom)` from all layers listed in capabilities by the server.

The default limit should be 18 as until now, but in case a tileset has maxzoom set to a higher number in metadata then the generated WMTS TlileMatrixSet must respect that maxzoom and increase the number appropriately.

**Comment by klokan** [comment]
Thanks @daliborjanak. Deploy to wmts.maptiler.com?

@chriswalker88 could you please test this fix?

**Comment by daliborjanak** [comment]
Deployed in wmts.maptiler.com. In future we could use tileserver-php in wmts.maptiler as submodule (i planned it before). It will be easier to fix problems like this. tileserver-php is designed to use as wmts submodule, clearly with php namespaces.

**Comment by klokan** [comment]
From @chriswalker88 (PLEASE WRITE HERE CHRIS!!!)
> This most recent version seems to stop working with WMTS in QGIS,
I have tested all the versions of QGIS, 2.6 and 2.12, the most recent 2.14 is downloading but I suspect this is still a problem.
> You can connect to the server it shows the layers available, but wont render them.
I have tested this again with a very basic dataset (the one I sent you) and nothing loads up.

**Comment by daliborjanak** [comment]
I removed some warnings with different php configurations but it was not related wit this issue. I deployed layer with deepest zoomlevels there: http://localhost/tech/tileserver/wmts It works good in my QGIS 2.14. 

@chriswalker88 We cannot do more if you don't provide us your data

**Comment by klokan** [comment]
@daliborjanak WE HAVE THE DATA!

**Comment by daliborjanak** [comment]
@chriswalker88 On
http://labs.klokantech.com/tileserver-php/
http://labs.klokantech.com/tileserver-php/wmts
is your data (klokan provided it to me) with latest tieserver. I displayed it in QGIS 2.14:
![qgis-nls-wmts](https://cloud.githubusercontent.com/assets/1891090/13920025/0c9a57fa-ef71-11e5-8950-1c5b0f3fbcfc.png)

![qgis-nls-wmts2](https://cloud.githubusercontent.com/assets/1891090/13920029/11583d8e-ef71-11e5-9cbe-32be69d96e91.png)

TIlematrix is correctly generated to zoom 21 so this issue looks solved.

**Comment by chriswalker88** [comment]
Ok, Its looking like a fault with our instance of it.
