### ISSUE TITLE
Zoom controls not accessible in MapboxGL preview

### ISSUE THREAD

**Issue by aptogo** [klokantech/tileserver-php#78]
The layerList div overlaps the MapboxGL zoom controls in the MapboxGL preview and has a higher z-index. This means that the zoom controls cannot be clicked. See screenshot:

<img width="525" alt="screenshot 2016-04-18 12 22 05" src="https://cloud.githubusercontent.com/assets/442016/14602580/9fef6a04-0560-11e6-9ea7-becb8c8526ae.png">

Chrome Version 49.0.2623.112 (64-bit)

**Comment by daliborjanak** [comment]
I fixed it now. Thanks for reporting
