### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by hoogw** [klokantech/tileserver-php#80]
I got error No 'Access-Control-Allow-Origin' header is present on the requested resource,

XMLHttpRequest cannot load,......Origin 'http://localhost:100' is therefore not allowed access.

I put tileserver on php on a different domain hosting.

when I run the website from localhost, which send request to remote tileserver (domain hosting), I got above error. 

I understand why, it is because of cross domain. But is there any simple solution to solve it?

By the way, tileserver is excellent, I failed upload to mapbox account because of 500k max tile size limit. That send me to this tileserver.  mapbox set 500k max tile size, can only host a small one or two layer shape file, I have 10+ layers, never be able to upload to it.

**Comment by klokan** [comment]
Glad to hear you enjoy using the TileServer-PHP project...

The CORS headers are set in TileServer-PHP everywhere and I believe correctly. You can also enable it in .htaccess as extra.

Please provide more details about the exact request on which you receive the CORS error.
Your bug report does not tell anything about how to reproduce your the problem.

Best is to give URL to the live tileserver instance.

**Comment by hoogw** [comment]
This is error message

XMLHttpRequest cannot load http://vectortile.mydomain/city/13/1411/3282.pbf. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:100' is therefore not allowed access.

I setup subdomain as 
vectortile.mydomain =  http://mydomain/tileserver/tileserver.php?/index.json?/

So if i run http://vectortile.mydomain/city/13/1411/3282.pbf from my local pc, it correctly response the file.

If i run website http://localhost:100/mywebsite,  I get above error.

**Comment by hoogw** [comment]
The CORS headers are set in TileServer-PHP everywhere and I believe correctly. You can also enable it in .htaccess as extra.  ------ good advise thanks to @klokan 


I had try many vector tile server, this is the only one works for me. And it is unbelievable easy to setup. Just unzip to apache server, that is it. 
It can host as many mbtiles as you want. 

As of today, it is the number one choice for me among the many.
I can't believe it is not list on [https://github.com/mapbox/awesome-vector-tiles](url)
It should has a place on above list, since I had try all serve on this list, but none of them works for me, either failed installation or only host one mbtile one time. Only this one works perfectly for me.
