### ISSUE TITLE
Is full source available?

### ISSUE THREAD

**Issue by johnsercel** [klokantech/tileserver-php#81]
TileServer seems critically dependent on the javascript hosted at cdn.klokantech.com/tileviewer/v1/index.js, which is heavily minified. Is the source code for that javascript available anywhere? Thanks!

**Comment by daliborjanak** [comment]
No the source code is more complicated and private. But you can use your own viewer. I wrote example of usage to wiki https://github.com/klokantech/tileserver-php/wiki. I thing it helps you. You can use template posted in related ticket https://github.com/klokantech/tileserver-php/issues/31 in leaflet. We will give more examples of viewers later.

**Comment by klokan** [comment]
All server functions of the TileServer-PHP are 100% open-source - serving the tiles, TileJSON, using from MapBox Studio, Leaflet, etc.
Your can remove our "tileviewer" frontend and server runs just fine - if you use your own viewer or load tiles from a different location or your own application (possibly running even on a different server).

You can also switch the TileServer-PHP project to use a custom template - as @daliborjanak suggested.

In future we may release our "tileviewer" component as open-source, but right now it would require extra effort related to cleaning and documenting the code - so it does not make much sense. BTW the tileviewer component is designed to run on top of multiple backends (tiles generated by MapTiler accessed via file:// protocol, tiles in tileserver-php, tileserver-mapnik, tileserver-gl, tiles hosted on Amazon S3, Google Cloud Storage, TileServer.com, tiles on https with Google Drive or Dropbox free hosting, or any TileJSON endpoint, etc.).

**Comment by johnsercel** [comment]
Okay, thank you. I've been working on a GAE/GCS hybrid deployment, which needs some optimizations such as direct tile requests, no proxy. But I'll work on a different front end.

**Comment by klokan** [comment]
The documentation updated:
https://github.com/klokantech/tileserver-php/wiki/Template
