### ISSUE TITLE
Lacking style

### ISSUE THREAD

**Issue by ScaredyCat** [klokantech/tileserver-php#82]
Perhaps I'm missing something, but the instructions are pretty sparse. I have an apache server setup fine and it's sort of working. I say sort of because there's limited colour in the map. The background is black on which I've got blue and brown lines; 

![nastymap](https://cloud.githubusercontent.com/assets/168872/14725774/d5efbbce-0815-11e6-8753-e2083222a427.png)

I can't for the life of me find anything that hints at using an alternative style. Am I missing something obvious, is there any documentation?

**Comment by klokan** [comment]
TileServer-PHP is serving the raw PBF tiles.

If you want your own style with such vector tiles you have to host a few assets extra - the JSON style itself, font glyphs, probably offline version of MapBox GL JS javascript.

For step-by-step documentation see: http://osm2vectortiles.org/docs/display-map-with-mapbox-gl and https://github.com/klokantech/osm2vectortiles-gl-styles

We work now on another project - the TileServer-GL - which is made to serve vector tiles together with styles and assets, and which is also able to render visually equal raster tiles for older clients on the server side. Check: https://github.com/klokantech/tileserver-gl/

**Comment by ScaredyCat** [comment]
Perfect, that's for the pointers.
