### ISSUE TITLE
geojson->mbt->tileserver: No data presented.

### ISSUE THREAD

**Issue by Synesso** [klokantech/tileserver-php#83]
I wish to construct a pipleline that takes GeoJSON through to self-hosted MapBox vector tiles specification. 

- Tippecanoe converts geojson to .mbt
- mbutil converts mbt to tiles
- tileserver-php exposes endpoint for tiles.

Tippecanoe & mbutil both show lots of promising output, indicating they are working. But when I look at the collection on tileserver it is empty. 

I fully suspect that this may turn out to be user error. At the very least it may provide input to a more robust README, so that newbies like me don't trip over themselves. 

I've x-posted this as a [question on gis.stackexchange.com](http://gis.stackexchange.com/questions/193095/generating-and-hosting-vector-tiles-from-geojson-no-errors-but-no-data) - more details are present there.

**Comment by klokan** [comment]
Why don't you just try to put the .mbtiles file directly next to tileserver.php?

There is no need to use mbutil.

**Comment by Synesso** [comment]
Yes, I tried that also. In that case, no collection was found at all.

**Comment by Synesso** [comment]
Just two files, edge-speed.mbt & tileserver.php side-by-side.

**Comment by Synesso** [comment]
Solved in stackexchange. I needed to include .htaccess & rename edge-speed.mbt to edge-speed.mbtiles
