### ISSUE TITLE
custom tiles and wmts

### ISSUE THREAD

**Issue by KlemenSpruk** [klokantech/tileserver-php#84]
Hello!

Is there any way or other server that can serve local custom tiles made with MapTiler via WMTS service?
Will tileserver support such a feature in future?

Thanks! 

Klemen

**Comment by klokan** [comment]
Not very clear description of an issue...

TileServer-PHP serves already WMTS for local custom tiles made with MapTIler. See: http://www.maptiler.com/how-to/tileserver-php/ for how to use it.

TileServer-PHP can also serve WMTS for tiles hosted on a different server (remote location such as Amazon S3, Google Cloud Storage, your own server, etc.). This has been implemented in #69 and discussed on MapTiler User Group.

We also provide a free online service which turns MapTiler tiles hosted anywhere into OGC WMTS - just provide link to 'metadata.json' to http://wmts.maptiler.com/ - and you can open your tiles in ArcGIS, QGIS or other WMTS clients.

**Comment by KlemenSpruk** [comment]
Hello again!

I have tiled my *.tiff images with MapTiler. 
My settings were Advanced tiles - Custom coordinate system
Generated metadata.json is:
{
  "name": "d48_test_1",
  "version": "1.1.0",
  "description": "",
  "type": "overlay",
  "format": "png",
  "minzoom": "14",
  "maxzoom": "14",
  "bounds": [0.00000000, 0.00000000, 0.00000000, 0.00000000],
  "scale": "1",
  "profile": "custom",
  "crs": "EPSG:50000",
  "proj4": "+proj=tmerc +lat_0=0 +lon_0=15 +k=0.9999 +x_0=500000 +y_0=-5000000 +ellps=bessel +towgs84=409.545,72.164,486.872,3.085957,5.46911,-11.020289,17.919665 +units=m +no_defs ",
  "extent": [392249.97500000, 41000.02500000, 611749.97500000, 174250.02500000],
  "tile_matrix": [
  {
    "id": "0",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [409.60000000, -409.60000000],
    "scale_denominator": 1462857.14285714
  },
  {
    "id": "1",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [204.80000000, -204.80000000],
    "scale_denominator": 731428.57142857
  },
  {
    "id": "2",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [102.40000000, -102.40000000],
    "scale_denominator": 365714.28571429
  },
  {
    "id": "3",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [51.20000000, -51.20000000],
    "scale_denominator": 182857.14285714
  },
  {
    "id": "4",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [25.60000000, -25.60000000],
    "scale_denominator": 91428.57142857
  },
  {
    "id": "5",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [12.80000000, -12.80000000],
    "scale_denominator": 45714.28571429
  },
  {
    "id": "6",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [6.40000000, -6.40000000],
    "scale_denominator": 22857.14285714
  },
  {
    "id": "7",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [3.20000000, -3.20000000],
    "scale_denominator": 11428.57142857
  },
  {
    "id": "8",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [1.60000000, -1.60000000],
    "scale_denominator": 5714.28571429
  },
  {
    "id": "9",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [0.80000000, -0.80000000],
    "scale_denominator": 2857.14285714
  },
  {
    "id": "10",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [0.40000000, -0.40000000],
    "scale_denominator": 1428.57142857
  },
  {
    "id": "11",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [0.20000000, -0.20000000],
    "scale_denominator": 714.28571429
  },
  {
    "id": "12",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [0.10000000, -0.10000000],
    "scale_denominator": 357.14285714
  },
  {
    "id": "13",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [0.05000000, -0.05000000],
    "scale_denominator": 178.57142857
  },
  {
    "id": "14",
    "tile_size": [512, 512],
    "origin": [343591.00000000, 224162.00000000],
    "extent": [343591.00000000, 1907.00000000, 653077.00000000, 224162.00000000],
    "pixel_size": [0.02500000, -0.02500000],
    "scale_denominator": 89.28571429
  }
]
}

I have tileserver running local on my vagrant box. I can display tiles tiled in WebMercator Google XYZ scheme from my local WMTS service but i cant display tiles generated with option Advanced tiles - Custom coordinate system

**Comment by klokan** [comment]
While reading the comment you have posted here and deleted - it seems you have used an old version of the tileserver-php.

**Comment by KlemenSpruk** [comment]
Hello!

I used https://github.com/klokantech/tileserver-php <https://github.com/klokantech/tileserver-php>.

I deleted the comment because I got it working in qgis. Thank for your answer, it was really helpful although I dindn decribe the problem enough. I had an error in metadata.json file. 

But it I still cant view tiles in arcMap.   Any advice?

Bellow is my GetCapabilities xml.
I can display this layer withou any problem in qgis but in arc map it is not rendered.

<Capabilities xmlns="http://www.opengis.net/wmts/1.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml"xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd" version="1.0.0">

<ows:ServiceIdentification>
<ows:Title>tileserverphp</ows:Title>
<ows:ServiceType>OGC WMTS</ows:ServiceType>
<ows:ServiceTypeVersion>1.0.0</ows:ServiceTypeVersion>
</ows:ServiceIdentification>

<ows:OperationsMetadata>
<ows:Operation name="GetCapabilities">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="http://wmts.fmp.flycom.si:99/tileserver.php?/wmts?/wmts/1.0.0/WMTSCapabilities.xml?/wmts/1.0.0/WMTSCapabilities.xml">
<ows:Constraint name="GetEncoding">
<ows:AllowedValues>
<ows:Value>RESTful</ows:Value>
</ows:AllowedValues>
</ows:Constraint>
</ows:Get>

<ows:Get xlink:href="http://wmts.fmp.flycom.si:99/tileserver.php?/wmts?/wmts/1.0.0/WMTSCapabilities.xml?/wmts?">
<ows:Constraint name="GetEncoding">
<ows:AllowedValues>
<ows:Value>KVP</ows:Value>
</ows:AllowedValues>
</ows:Constraint>
</ows:Get>
</ows:HTTP>
</ows:DCP>
</ows:Operation>
<ows:Operation name="GetTile">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="http://wmts.fmp.flycom.si:99/tileserver.php?/wmts?/wmts/1.0.0/WMTSCapabilities.xml?/wmts/">
<ows:Constraint name="GetEncoding">
<ows:AllowedValues>
<ows:Value>RESTful</ows:Value>
</ows:AllowedValues>
</ows:Constraint>
</ows:Get>
<ows:Get xlink:href="http://wmts.fmp.flycom.si:99/tileserver.php?/wmts?/wmts/1.0.0/WMTSCapabilities.xml?/wmts?">
<ows:Constraint name="GetEncoding">
<ows:AllowedValues>
<ows:Value>KVP</ows:Value>
</ows:AllowedValues>
</ows:Constraint>
</ows:Get>
</ows:HTTP>
</ows:DCP>
</ows:Operation>
</ows:OperationsMetadata>
<Contents>
<Layer>
<ows:Title>ortho14</ows:Title>
<ows:Identifier>ortho14</ows:Identifier>
<ows:WGS84BoundingBox crs="urn:ogc:def:crs:OGC:2:84">
<ows:LowerCorner>13.58470946 45.44901459</ows:LowerCorner>
<ows:UpperCorner>16.19763671 46.69458211</ows:UpperCorner>
</ows:WGS84BoundingBox>
<Style isDefault="true">
<ows:Identifier>default</ows:Identifier>
</Style>
<Format>image/png</Format>
<TileMatrixSetLink>
<TileMatrixSet>custom3912ortho14</TileMatrixSet>
</TileMatrixSetLink>
<ResourceURL format="image/png" resourceType="tile" template="http://wmts.fmp.flycom.si:99/tileserver.php?/wmts?/wmts/1.0.0/WMTSCapabilities.xml?/ortho14/{TileMatrix}/{TileCol}/{TileRow}.png"/>
</Layer>
<TileMatrixSet>
<ows:Title>custom3912ortho14</ows:Title>
<ows:Abstract>custom3912ortho14 EPSG:3912</ows:Abstract>
<ows:Identifier>custom3912ortho14</ows:Identifier>
<ows:SupportedCRS>urn:ogc:def:crs:EPSG::3912</ows:SupportedCRS>
<TileMatrix>
<ows:Identifier>0</ows:Identifier>
<ScaleDenominator>1462857.1428571</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>2</MatrixWidth>
<MatrixHeight>2</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>1</ows:Identifier>
<ScaleDenominator>731428.57142857</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>3</MatrixWidth>
<MatrixHeight>3</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>2</ows:Identifier>
<ScaleDenominator>365714.28571429</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>6</MatrixWidth>
<MatrixHeight>5</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>3</ows:Identifier>
<ScaleDenominator>182857.14285714</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>12</MatrixWidth>
<MatrixHeight>9</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>4</ows:Identifier>
<ScaleDenominator>91428.57142857</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>24</MatrixWidth>
<MatrixHeight>17</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>5</ows:Identifier>
<ScaleDenominator>45714.28571429</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>48</MatrixWidth>
<MatrixHeight>34</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>6</ows:Identifier>
<ScaleDenominator>22857.14285714</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>95</MatrixWidth>
<MatrixHeight>68</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>7</ows:Identifier>
<ScaleDenominator>11428.57142857</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>189</MatrixWidth>
<MatrixHeight>136</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>8</ows:Identifier>
<ScaleDenominator>5714.28571429</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>378</MatrixWidth>
<MatrixHeight>272</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>9</ows:Identifier>
<ScaleDenominator>2857.14285714</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>756</MatrixWidth>
<MatrixHeight>543</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>10</ows:Identifier>
<ScaleDenominator>1428.57142857</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>1512</MatrixWidth>
<MatrixHeight>1086</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>11</ows:Identifier>
<ScaleDenominator>714.28571429</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>3023</MatrixWidth>
<MatrixHeight>2171</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>12</ows:Identifier>
<ScaleDenominator>357.14285714</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>6045</MatrixWidth>
<MatrixHeight>4341</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>13</ows:Identifier>
<ScaleDenominator>178.57142857</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>12090</MatrixWidth>
<MatrixHeight>8682</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>14</ows:Identifier>
<ScaleDenominator>89.28571429</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>24179</MatrixWidth>
<MatrixHeight>17364</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>15</ows:Identifier>
<ScaleDenominator>44.64285714</ScaleDenominator>
<TopLeftCorner>343591 224162</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>48358</MatrixWidth>
<MatrixHeight>34728</MatrixHeight>
</TileMatrix>
</TileMatrixSet>
<TileMatrixSet>
<ows:Title>GoogleMapsCompatible</ows:Title>
<ows:Abstract>GoogleMapsCompatible EPSG:3857</ows:Abstract>
<ows:Identifier>GoogleMapsCompatible</ows:Identifier>
<ows:SupportedCRS>urn:ogc:def:crs:EPSG::3857</ows:SupportedCRS>
<TileMatrix>
<ows:Identifier>0</ows:Identifier>
<ScaleDenominator>559082264.02872</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>1</MatrixWidth>
<MatrixHeight>1</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>1</ows:Identifier>
<ScaleDenominator>279541132.01436</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>4</MatrixWidth>
<MatrixHeight>4</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>2</ows:Identifier>
<ScaleDenominator>139770566.00718</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>16</MatrixWidth>
<MatrixHeight>16</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>3</ows:Identifier>
<ScaleDenominator>69885283.00359</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>64</MatrixWidth>
<MatrixHeight>64</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>4</ows:Identifier>
<ScaleDenominator>34942641.501795</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>256</MatrixWidth>
<MatrixHeight>256</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>5</ows:Identifier>
<ScaleDenominator>17471320.750897</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>1024</MatrixWidth>
<MatrixHeight>1024</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>6</ows:Identifier>
<ScaleDenominator>8735660.3754487</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>4096</MatrixWidth>
<MatrixHeight>4096</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>7</ows:Identifier>
<ScaleDenominator>4367830.1877244</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>16384</MatrixWidth>
<MatrixHeight>16384</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>8</ows:Identifier>
<ScaleDenominator>2183915.0938622</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>65536</MatrixWidth>
<MatrixHeight>65536</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>9</ows:Identifier>
<ScaleDenominator>1091957.5469311</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>262144</MatrixWidth>
<MatrixHeight>262144</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>10</ows:Identifier>
<ScaleDenominator>545978.77346554</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>1048576</MatrixWidth>
<MatrixHeight>1048576</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>11</ows:Identifier>
<ScaleDenominator>272989.38673277</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>4194304</MatrixWidth>
<MatrixHeight>4194304</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>12</ows:Identifier>
<ScaleDenominator>136494.69336639</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>16777216</MatrixWidth>
<MatrixHeight>16777216</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>13</ows:Identifier>
<ScaleDenominator>68247.346683193</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>67108864</MatrixWidth>
<MatrixHeight>67108864</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>14</ows:Identifier>
<ScaleDenominator>34123.673341597</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>268435456</MatrixWidth>
<MatrixHeight>268435456</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>15</ows:Identifier>
<ScaleDenominator>17061.836670798</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>1073741824</MatrixWidth>
<MatrixHeight>1073741824</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>16</ows:Identifier>
<ScaleDenominator>8530.9183353991</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>4294967296</MatrixWidth>
<MatrixHeight>4294967296</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>17</ows:Identifier>
<ScaleDenominator>4265.4591676996</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>17179869184</MatrixWidth>
<MatrixHeight>17179869184</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>18</ows:Identifier>
<ScaleDenominator>2132.7295838498</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>68719476736</MatrixWidth>
<MatrixHeight>68719476736</MatrixHeight>
</TileMatrix>
</TileMatrixSet>
<TileMatrixSet>
<ows:Title>WGS84</ows:Title>
<ows:Abstract>WGS84 EPSG:4326</ows:Abstract>
<ows:Identifier>WGS84</ows:Identifier>
<ows:SupportedCRS>urn:ogc:def:crs:EPSG::4326</ows:SupportedCRS>
<TileMatrix>
<ows:Identifier>0</ows:Identifier>
<ScaleDenominator>279541132.01436</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>2</MatrixWidth>
<MatrixHeight>1</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>1</ows:Identifier>
<ScaleDenominator>139770566.00718</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>8</MatrixWidth>
<MatrixHeight>4</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>2</ows:Identifier>
<ScaleDenominator>69885283.00359</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>32</MatrixWidth>
<MatrixHeight>16</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>3</ows:Identifier>
<ScaleDenominator>34942641.501795</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>128</MatrixWidth>
<MatrixHeight>64</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>4</ows:Identifier>
<ScaleDenominator>17471320.750897</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>512</MatrixWidth>
<MatrixHeight>256</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>5</ows:Identifier>
<ScaleDenominator>8735660.3754487</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>2048</MatrixWidth>
<MatrixHeight>1024</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>6</ows:Identifier>
<ScaleDenominator>4367830.1877244</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>8192</MatrixWidth>
<MatrixHeight>4096</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>7</ows:Identifier>
<ScaleDenominator>2183915.0938622</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>32768</MatrixWidth>
<MatrixHeight>16384</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>8</ows:Identifier>
<ScaleDenominator>1091957.5469311</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>131072</MatrixWidth>
<MatrixHeight>65536</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>9</ows:Identifier>
<ScaleDenominator>545978.77346554</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>524288</MatrixWidth>
<MatrixHeight>262144</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>10</ows:Identifier>
<ScaleDenominator>272989.38673277</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>2097152</MatrixWidth>
<MatrixHeight>1048576</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>11</ows:Identifier>
<ScaleDenominator>136494.69336639</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>8388608</MatrixWidth>
<MatrixHeight>4194304</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>12</ows:Identifier>
<ScaleDenominator>68247.346683193</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>33554432</MatrixWidth>
<MatrixHeight>16777216</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>13</ows:Identifier>
<ScaleDenominator>34123.673341597</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>134217728</MatrixWidth>
<MatrixHeight>67108864</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>14</ows:Identifier>
<ScaleDenominator>17061.836670798</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>536870912</MatrixWidth>
<MatrixHeight>268435456</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>15</ows:Identifier>
<ScaleDenominator>8530.9183353991</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>2147483648</MatrixWidth>
<MatrixHeight>1073741824</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>16</ows:Identifier>
<ScaleDenominator>4265.4591676996</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>8589934592</MatrixWidth>
<MatrixHeight>4294967296</MatrixHeight>
</TileMatrix>
<TileMatrix>
<ows:Identifier>17</ows:Identifier>
<ScaleDenominator>2132.7295838498</ScaleDenominator>
<TopLeftCorner>90 -180</TopLeftCorner>
<TileWidth>512</TileWidth>
<TileHeight>512</TileHeight>
<MatrixWidth>34359738368</MatrixWidth>
<MatrixHeight>17179869184</MatrixHeight>
</TileMatrix>
</TileMatrixSet>
</Contents>
<ServiceMetadataURL xlink:href="http://wmts.fmp.flycom.si:99/tileserver.php?/wmts?/wmts/1.0.0/WMTSCapabilities.xml?/wmts/1.0.0/WMTSCapabilities.xml"/>
</Capabilities>

Metadata from mgaptiler:


> On 27 May 2016, at 13:22, Petr Pridal <notifications@github.com> wrote:
> 
> While reading the comment you have posted here and deleted - it seems you have used an old version of the tileserver-php.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/klokantech/tileserver-php/issues/84#issuecomment-222122876>, or mute the thread <https://github.com/notifications/unsubscribe/AIjlnXQfWFyOpNxOZh-kzT5NgSyXl9hwks5qFtPxgaJpZM4Inlc->.
> 

Best regards / Lep pozdrav

Klemen Spruk | Geoinformatics analyst, Developer / Geoinformatik, Razvijalec
Flycom d.o.o., Moste 26b, SI4247 Zirovnica, Slovenia

www.flycom.si <http://www.flycom.si/> | klemen.spruk@flycom.si <mailto:klemen.spruk@flycom.si> 

Notice: This email and any attachments hereto may contain private, confidential, and/or privileged material for the sole use of the intended recipient and is the property of Flycom d.o.o.. Any review, copying, or distribution of this email or any attachments thereto by others is strictly prohibited. If you are not the intended recipient, please contact the sender immediately and permanently delete the original and any copies of this email and any attachments hereto.

**Comment by klokan** [comment]
I expect by using http://wmts.maptiler.com/ everything runs as it should.

We can offer you one-to-one support, where we can ensure the problem related to your data is solved. Check http://www.maptiler.com/support/one-to-one/.

You pay one hour of our time, provide report submitted via MapTIler (http://www.maptiler.com/how-to/submit-report/ or -report on CLI) and some of your sample data - so that we can reproduce your problem, and we fix the issue or recommend how to repair your workflow so this runs.

**Comment by KlemenSpruk** [comment]
Hello!

I found the problem which is a bug in ESRI ArcMap 10.2. Tiles are not requested when scale is smaller than 1000. When using newer ArcMap version everything works fine.

Thank for your help!

Klemen
