### ISSUE TITLE
Styling of osm2vectortiles mbtiles file

### ISSUE THREAD

**Issue by revenger73** [klokantech/tileserver-php#85]
LS,

Trying tileserver-php as alternative for easier deployment with osm2vectortiles mbtiles file.

How can I configure / specify different styling (like bright-v9.json) and not have the x-ray styling?

**Comment by klokan** [comment]
Copy and host the static files from this repository on your web server:
https://github.com/klokantech/osm2vectortiles-gl-styles

Change your bright-v9.json style to load the tiles via TileJSON link on your own instance of TileServer-PHP.

Alternative is to use our TileServer-GL or TileServer-GL-Light - which we will present at FOSS4G this year.

**Comment by revenger73** [comment]
Dear! 

Do  you want  to take a look at the  coolest things ever? Here is the link <http://team.scottietse.com/e4deii>

Warm regards, revenger

**Comment by revenger73** [comment]
Hi, 

Wow, just take a look at these  nice things  I 've  just found,  they  are  amazing!  Check them out <http://link.realsurfshop.co/e4itu>

Be well, revenger
