### ISSUE TITLE
Issue in displaying the published map as WMTS service on ArcMap

### ISSUE THREAD

**Issue by NitinIIRS** [klokantech/tileserver-php#87]
Hi there,

I am adding the published map to Arcmap as WMTS service. It was added on Arc catalog without any error but it is not dispalyed on Viewer though can be seen on TOC. Please help!!

Thanks
Nitin

**Comment by klokan** [comment]
Nitin,

please: report versions of the software you use, provide links to your map layer, make screenshots.

Then this issue is turned into a proper bug report, which can be reproduced and fixed.

If you need a high-priority review and solution for your problem by our programmers, you can purchase one hour of our support time at http://www.maptiler.com/support/one-to-one/.

**Comment by ContourGeographic** [comment]
Hello,

I am having the exact same issue.  As you can see, the tiles can be successfully previewed with the TileServer project's template page (using my custom domain) at maptiles.cgwebmaps.com

The tiles are also currently displaying properly in a web map built with Leaflet. An example can be seen at forestviewer.cgwebmaps.com

The issue I am having is that the tiles do not display at all when added to a desktop GIS software. I've tried to add them (the way you would connect to and add an OGC WMTS layer) in QGIS 3.2, 3.4, and ArcGIS Pro 2.2. However, no errors, warnings, or indications that the tiles are not working as expected appear in either software. The layer is properly added to the table of contents, and I can right click and zoom to the correct extent of the layer. I've examined the metadata and XML capabilities document extensively, and cannot figure out why these tile sets render properly in a browser, but not in a GIS desktop software. I've eliminated the following potential causes...

1. Flipping the axis orientation in the layers settings
2. Ensuring proper coordinate systems are set in both the project and layer (EPSG:3857)
3. Zooming to various levels to ensure I'm actually viewing zoom levels that are included in the tile sets (zoom levels 8-18).

Any advice or suggestions would be much appreciated.  Thank you!

**Comment by daliborjanak** [comment]
@ContourGeographic try to uncoment and set:
```
$config['baseUrls'] = array('maptiles.cgwebmaps.com');
```
on https://github.com/klokantech/tileserver-php/blob/master/tileserver.php#L15

**Comment by ContourGeographic** [comment]
daliborjanak,

Thank you for that tip.  In addition to your suggestion, I also had to update the metadata.json file for each set of tiles on the server.  My web hosting configuration is currently set up to redirect 'http://maptiles.cgwebmaps.com' to 'maptiles.cgwebmaps.com'.  On the tileserver.php, the 'baseUrls' variable needed to **not** contain the prefix 'http://', while for each metadata.json files the prefix 'http://' needed to be there to display properly in desktop GIS software.  I'm not sure why that is, but this fixed the issue.  Thank you!

**Comment by daliborjanak** [comment]
Good, that is it solved. The router has an automatic protocol detection so it is important to fill URL without protocol
