### ISSUE TITLE
mbtiles in Qgis

### ISSUE THREAD

**Issue by lorenzoperone** [klokantech/tileserver-php#89]
HI,
I've installed on Mac OS via Kinematic the Docker tileserver-php and I've configured a directory containing the mbtiles of Italy downloaded via http://osm2vectortiles.org/.
I'm able to add the WMTS service at the address http://192.168.99.100:32773/wmts and Qgis discover an image/pbf source but I can't add the layer.
It depends by the fact that Qgis can use an image source (es. tiff or ecw) but it can't load the vector-tile source?
Thanks.
Lorenzo

**Comment by clientportal** [comment]
QGIS is not able to read the vector tiles in pbf format (MVT) - and WMTS is not able to serve this format either.

You have to turn the vector tiles into raster tiles. For this you can use our TileServer GL project. Usage on Mac with Docker / Kitematic is as easy as with tileserver php. See:
 http://blog.klokantech.com/2016/08/tileserver-gl-maps-with-gl-json-styles.html

TileServer PHP project is never going to be rasterizing the vector tiles - it will only serve them to client which are able to read it (such as MapBox GL JS, OpenLayers3, Mapbox Android + iOS SDK, etc.)

**Comment by lorenzoperone** [comment]
Thanks,
I'll try it.
Lorenzo
