### ISSUE TITLE
Installation and setup instructions?

### ISSUE THREAD

**Issue by jdaniel-GIS** [klokantech/tileserver-php#90]
I have an mbtiles files/directory of pbf files I would like to serve. But I have not come up with any combination of settings that works.

What is supposed to go into $config['dataRoot']?
Apparently there is supposed to be a json file in the directory too. What should it be named? In my case, I renamed my tileserver php file to be index.php. It seems to want an index.json file. But what are the parameters of that? I have tried to fill it in according to the examples. But then I get undefined Javascript errors. 

I tried using the countries example motiles file. Apparently, that makes it seem to want a countries.json file too. 

Can you give me any hints?

**Comment by jdaniel-GIS** [comment]
Never mind. I don't need this project at all. I can serve this data with node mbtiles.

**Comment by daliborjanak** [comment]
You need LAMP. Just copy mbtiles to a directory with tileserver-php. TileServer will scan dirs and create index.json itself. Readem or tutorial for raster is here http://www.maptiler.com/how-to/tileserver-php/. Vectors have same behavior
